window.MAP_SEARCH_CONFIG = {
  HOTPEPPER_API_KEY: "",
  VALUECOMMERCE_SID: "",
  VALUECOMMERCE_PID: "",
  VALUECOMMERCE_URL_TEMPLATE: "",
  RAKUTEN_APPLICATION_ID: "",
  RAKUTEN_ACCESS_KEY: "",
  RAKUTEN_AFFILIATE_ID: "",
  HOTEL_AFFILIATE_URL: "",
  PARKING_AFFILIATE_URL: "",
  TAXI_AFFILIATE_URL: "",
  BEAUTY_AFFILIATE_URL: "",
};
